x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: "50m"
    max-file: 6
x-network: &default-network
  internal:
x-base: &base
  depends_on:
    pgsql:
      condition: service_healthy
    valkey:
      condition: service_healthy
    ssr:
      condition: service_healthy
  image: ${IMAGE_NAME:-app}:latest
  env_file:
    - .env.production
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  security_opt:
    - no-new-privileges:true
  volumes:
    - 'storage_public:/app/storage/app/public'
    - 'storage_logs:/app/storage/logs'
  logging: *default-logging
  restart: always

services:
  app:
    <<: *base
    build:
      target: app
    command: ["php", "/var/www/html/artisan", "octane:start", "--server=frankenphp", "--port=8000"]
    stop_signal: SIGTERM
    environment:
      AUTORUN_ENABLED: true
      INERTIA_SSR_URL: http://ssr:13714
      INERTIA_SSR_ENSURE_BUNDLE_EXISTS: false
      PHP_OPCACHE_ENABLE: "1"
    networks:
      - internal
      - proxy
    healthcheck:
      test: ["CMD", "healthcheck-octane"]
      start_period: 10s
    labels:
      traefik.enable: true
      traefik.http.routers.fadogen.rule: Host(`${APP_HOST}`)
      traefik.http.services.fadogen.loadbalancer.server.port: 8000
      # Health check
      traefik.http.services.fadogen.loadbalancer.healthcheck.path: "/up"
      traefik.http.services.fadogen.loadbalancer.healthcheck.interval: "30s"
      traefik.http.services.fadogen.loadbalancer.healthcheck.timeout: "5s"
      traefik.http.services.fadogen.loadbalancer.healthcheck.scheme: "http"

  horizon:
    <<: *base
    command: ["php", "/var/www/html/artisan", "horizon"]
    stop_signal: SIGTERM
    networks: *default-network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-horizon"]
      start_period: 10s

  scheduler:
    <<: *base
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    networks: *default-network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s

#  reverb:
#    <<: *base
#    command: ["php", "/var/www/html/artisan", "reverb:start", "--port=8080"]
#    stop_signal: SIGTERM
#    networks: *default-network
#    depends_on:
#      app:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "healthcheck-reverb"]
#      start_period: 10s

  ssr:
    image: ${IMAGE_NAME:-app}:ssr
    build:
      target: ssr
    security_opt:
      - no-new-privileges:true
    networks: *default-network
    logging: *default-logging
    restart: always
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:13714/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 3

  valkey:
    image: 'valkey/valkey:alpine'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [ "valkey-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "2gb" ]
    security_opt:
      - no-new-privileges:true
    volumes:
      - 'stack-valkey:/data'
    logging: *default-logging
    networks: *default-network
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      retries: 3
      timeout: 5s
    restart: always

  pgsql:
    image: 'postgres:17-bookworm'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
        # command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    security_opt:
      - no-new-privileges:true
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      # - './postgresql.conf:/etc/postgresql/postgresql.conf'
      - 'stack-pgsql:/var/lib/postgresql/data'
    networks: *default-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      interval: 15s
      retries: 12
      timeout: 20s
    restart: always
    logging: *default-logging

networks:
  internal:
  proxy:
    external: true

volumes:
  storage_public:
  storage_logs:
  stack-pgsql:
  stack-valkey:

