---
- name: Test de connexion
  ping:

- name: Mise à jour et nettoyage du système
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes
    force_apt_get: yes
  register: apt_upgrade
  become: true

- name: Redémarrage si nécessaire
  ansible.builtin.reboot:
  when: apt_upgrade.changed and ansible_pkg_mgr == "apt" and
    ansible_reboot_required | default(false)
  become: true